services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://gradprofile.com/api
    volumes:
      - uploads:/app/uploads
      - data:/app/backend/data
    restart: always

volumes:
  uploads:
  data: